--CREAR TABLESPACE 
CREATE TABLESPACE MID_TERM DATAFILE 
'MID_TERM .DBF' SIZE 60M;

--CREAR USUARIO CON PERMISOS DE CONEXION, DBA, Y CON ESPACIO ILIMITADO EN EL TABLESPACE.

CREATE USER SPALACIO
IDENTIFIED BY SPALACIO
DEFAULT TABLESPACE MID_TERM
--PERMISO ILIMITADO
QUOTA UNLIMITED ON MID_TERM;

--CREATE ROLES

CREATE USER PRACTICA1
IDENTIFIED BY PRACTICA1
DEFAULT TABLESPACE PRACTICA1
--PERMISO ILIMITADO
QUOTA UNLIMITED ON PRACTICA1;

CREATE ROLE MINI_DBA;
GRANT CREATE SESSION TO MINI_DBA; 
GRANT DBA TO MINI_DBA; 

CREATE ROLE STUDENT;
GRANT CREATE SESSION TO STUDENT; 
GRANT DBA TO STUDENT; 


GRANT MINI_DBA TO SPALACIO;

GRANT CONNECT TO SPALACIO; 

SHOW USER; 